services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=bluecomet
      - POSTGRES_DB=momsrecipes
    ports:
      - "5432:5432" #Only for local development, remove this line when deploying to AWS?

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"

    environment:
      - DB_SOURCE=postgresql://root:bluecomet@postgres:5432/momsrecipes?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"] #Here for future, but not needed now that migration moved to main code.
    command: [ "/app/main" ]