// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID                  int64  `json:"id"`
	Name                string `json:"name"`
	CalorieCountPerUnit int32  `json:"calorie_count_per_unit"`
}

type Recipe struct {
	ID                     int64     `json:"id"`
	Name                   string    `json:"name"`
	PreparationTimeInMins  int32     `json:"preparation_time_in_mins"`
	DifficultyLevel        int32     `json:"difficulty_level"`
	CuisineType            string    `json:"cuisine_type"`
	CalorieCountPerServing int32     `json:"calorie_count_per_serving"`
	ServingsCount          int32     `json:"servings_count"`
	PreparationSteps       string    `json:"preparation_steps"`
	UserID                 int64     `json:"user_id"`
	CreatedAt              time.Time `json:"created_at"`
}

type RecipeIngredient struct {
	ID           int64   `json:"id"`
	RecipeID     int32   `json:"recipe_id"`
	IngredientID int32   `json:"ingredient_id"`
	Quantity     float64 `json:"quantity"`
	Unit         string  `json:"unit"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	Password          []byte    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
